# Generated by Django 5.0.4 on 2024-04-23 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0005_alter_fotografia_foto'),
        ('galeria', '0006_alter_fotografia_foto'),
    ]

    operations = [
    ]
